### ISSUE TITLE
Speed up the content changes calculation

### ISSUE THREAD

**Issue by Reemh** [Reemh/taco_server#35]
After timing calculations 7f57f2d6c870d984f2fc8021ffe77aabd79cde3f
From the browser choosing both content and structural changes took 4 minutes, choosing only structure took 234.710 ms.
In another example (from python) a table diff calculation took 96.05 sec, the part that is for content is 96.04 sec and everything else is 0.01.

One idea would be to check for reordering at the beginning, then sort one of the table (intersection matrix part) based on the other one, then apply a standard python numpy matrix subtraction operation.
The result should be a diff matrix with all the changed values --> from this matrix we can get the min and max and normalize the diff matrix. Afterwards, we can convert this matrix to any JSON form we like..

**Comment by thinkh** [comment]
Sounds good! You might consider that you have to order the complete diff-matrix back to its original position.

**Comment by Reemh** [comment]
After using numpy arrays for IDs instead of lists and using matrices to calculate the diff instead of for loops, the calculations takes only ~3 seconds instead of ~90 in the old method.
However, the results look different for the HDF data (they look more reasonable in the new method). 
The results look the same for the sample taco files.

It could be that there's something related to reordering somewhere, as the taco data doesn't have any reordering. This to be processed later.
For now, content changes calculations cannot get faster, unless we find a way to log it (creating the diff content objects in this case takes about 3.4 out of 3.7 sec for the whole content changes calculations, so it's the part where the time is used).

**Comment by Reemh** [comment]
As an idea to speed up the log, find a way to apply a function on each cell of the matrix (it's already possible to apply a function on each row or column).
The function should be able to create a JSON object (or any other object that could be transferred to the client) of the diff values.
