### ISSUE TITLE
Improve the time for jsonify

### ISSUE THREAD

**Issue by Reemh** [Reemh/taco_server#36]
After measuring the time, jsonify the diff result takes about 2 minutes for MicroRNA data. 
This is the most of the time in the server while processing the diff takes at most 4 seconds (after enhancing it from 2 minutes).
To find an alternative for jsonify or a way to make it faster.

**Comment by Reemh** [comment]
Sample timing output:
'time initialization', 0.023901939392089844, 
'logging', 2.9558379650115967
'content: ', 3.2572059631347656
'time diff calculation', 3.2616519927978516
'time for jsonify', 145.71305322647095, 
'time for everything ', 148.99881505966187

Time in the browser 2.5 minutes

**Comment by Reemh** [comment]
I used `json.dumps()` function instead of `flask.jsonify()` and I got much faster results for the same datasets!
'time initialization', 0.0056650638580322266
'logging', 1.5901460647583008
'content: ', 1.7635149955749512
'time diff calculation', 1.766340970993042
**'time for jsonify', 11.991443872451782**
'time for everything ', 13.76372504234314

Time in the browser 14.2 **seconds**

**Comment by Reemh** [comment]
Open points:
1- The response type in the case of json.dumps() is a string, we can formulate a response and specify the header type as 'application/json'.
2- Try 'ujson' which should be even faster than the used one.
https://pypi.python.org/pypi/ujson

**Comment by Reemh** [comment]
Using the 'ujson' package I saved about 10 seconds compared to 'json'
'time initialization', 0.011253833770751953
'logging', 2.1422359943389893
'content: ', 2.326349973678589
'time diff calculation', 2.3333630561828613
**'time for jsonify', 0.36470484733581543**
'time for everything ', 2.7107808589935303

Time in the browser about **3.1 seconds**

**Comment by Reemh** [comment]
Done. 6fb2f0b72b2c0e17fef9dea64396f6c78d593a48
Now I create a flask response with the header type as json. (This takes only 0.0006 sec so it should not be a problem, and it should make it better to handle on the client side).
In total about 4 minutes were saved :grinning:

**Comment by mstreit** [comment]
Nice job!
